apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendancecrm-deployment
  namespace: attendance-crm
  labels:
    app: attendancecrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendancecrm
  template:
    metadata:
      labels:
        app: attendancecrm
    spec:
      serviceAccountName: attendance-crm  
      containers:
        - name: attendancecrm-container
          image: acrproduksaks.azurecr.io/attendancecrm:157
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__AttendanceCRM
              valueFrom:
                secretKeyRef:
                  name: attendance-crm-secrets
                  key: ConnectionStrings__AttendanceCRM
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: attendance-crm-secrets
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
          volumeMounts:                    
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:                             
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: attendance-crm-keyvault