trigger: 
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-secrets
  - name: WORKING_DIRECTORY
    value: terraform/

stages: 
  - stage: Validate
    jobs: 
      - job: TerraformPlan
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.10.5'
                  
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(WORKING_DIRECTORY)'
              backendServiceArm: 'service-connection-subscription'
              backendAzureRmResourceGroupName: 'rg-storage-uksouth'
              backendAzureRmStorageAccountName: 'storagestatefile001'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.aksstate'

          - task: TerraformTaskV4@4
            displayName: Terraform Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(WORKING_DIRECTORY)'
              
          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=tfplan'
              workingDirectory: '$(WORKING_DIRECTORY)'
              environmentServiceNameAzureRM: 'service-connection-subscription'
            env:
             TF_VAR_email_address : $(email_address)
             TF_VAR_hosted_zone_name : $(hosted_zone_name)  

          - task: PublishPipelineArtifact@1
            inputs: 
              targetPath: '$(WORKING_DIRECTORY)'
              artifact: tfplan
              publishLocation: pipeline

  - stage: Apply
    displayName: Apply 
    dependsOn: Validate
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs: 
      - deployment: TerraformApply
        displayName: Terraform Apply
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@1
                  displayName: Install Terraform
                  inputs:
                    terraformVersion: '1.10.5'
                
                - task: TerraformTaskV4@4
                  displayName: Terraform Init
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(WORKING_DIRECTORY)'
                    backendServiceArm: 'service-connection-subscription'
                    backendAzureRmResourceGroupName: 'rg-storage-uksouth'
                    backendAzureRmStorageAccountName: 'storagestatefile001'
                    backendAzureRmContainerName: 'tfstate'
                    backendAzureRmKey: 'terraform.aksstate'

                - task: DownloadPipelineArtifact@2
                  displayName: Download Terraform Plan
                  inputs:
                    artifact: tfplan
                    path: '$(WORKING_DIRECTORY)'

                - task: TerraformTaskV4@4
                  displayName: Terraform Apply
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(WORKING_DIRECTORY)'
                    commandOptions: '-input=false tfplan'
                    environmentServiceNameAzureRM: 'service-connection-subscription'
                  env:
                    TF_VAR_email_address: $(email_address)
                    TF_VAR_hosted_zone_name: $(hosted_zone_name)

                - script: | 
                    curl -X POST $(SLACK_WEBHOOK_URL) \
                    -H 'Content-type: application/json' \
                    --data "{
                    \"text\": \"*Terraform Apply Completed*\n Status: ✅ Success\n Branch: $(Build.SourceBranchName)\n Build: $(Build.BuildId)\"}"
                  displayName: Notify Slack

