apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: attendance-crm-keyvault
  namespace: attendance-crm
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: dd707132-c827-47e9-833e-fa9884a06b05
    keyvaultName: kv-prod-uks-aks-myapp-02
    tenantId: 5b051fd6-752a-4d1c-85b3-ad8f25061d76
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
  secretObjects:
    - secretName: attendance-crm-secrets
      type: Opaque
      data:
        - objectName: sql-connection-string
          key: ConnectionStrings__AttendanceCRM