apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: attendance-crm-keyvault
  namespace: attendance-crm
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: ${APPLICATION_CLIENT_ID}
    keyvaultName: ${KEY_VAULT_NAME}
    tenantId: ${TENANT_ID}
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
  secretObjects:
    - secretName: attendance-crm-secrets
      type: Opaque
      data:
        - objectName: sql-connection-string
          key: ConnectionStrings__AttendanceCRM