apiVersion: v1
kind: ServiceAccount
metadata:
  name: attendance-crm
  namespace: attendance-crm
  annotations:
    azure.workload.identity/client-id: ${APPLICATION_CLIENT_ID}
  labels:
    azure.workload.identity/use: "true"
