apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    azure.workload.identity/client-id: ${EXTERNAL_DNS_CLIENT_ID}
  labels:
    azure.workload.identity/use: "true"
